/**
 * Curated emoji catalog for the Skill/Playbook icon picker. Grouped like
 * macOS's emoji panel, but trimmed to ~300 of the most useful entries to
 * keep the picker scannable and memory cheap. Each entry is just
 * `{ emoji, name }`; we search by substring against `name`.
 *
 * Bias of the curation: Objects (tools/docs/tech) and People (roles &
 * professions) lead, since those are what users reach for when naming a
 * Skill or Playbook. Animals/Food/Travel categories are kept lighter.
 *
 * Every emoji currently used in the seeded skills + playbooks is included
 * verbatim (matching VS16 selectors where present) so the picker can
 * highlight the seeded icon as "currently selected" on open.
 *
 * The user can still type any emoji into the search box to use one that
 * isn't in this list (handled by the picker's "Use typed emoji" fallback).
 */

export interface EmojiEntry {
  emoji: string;
  name: string;
}

export interface EmojiCategory {
  id: string;
  label: string;
  /** Emoji shown in the bottom category-jump bar (macOS-style). */
  icon: string;
  emojis: readonly EmojiEntry[];
}

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  {
    id: "objects",
    label: "Objects",
    icon: "💡",
    emojis: [
      // Tech & devices — workhorses for engineering/devops/builder skills
      // (Objects is intentionally first — it carries the most picks.)
      { emoji: "⌚", name: "watch time" },
      { emoji: "📱", name: "mobile phone" },
      { emoji: "📲", name: "mobile with arrow sync" },
      { emoji: "💻", name: "laptop computer" },
      { emoji: "⌨️", name: "keyboard typing" },
      { emoji: "🖥", name: "desktop computer" },
      { emoji: "🖨", name: "printer" },
      { emoji: "🖱", name: "mouse" },
      { emoji: "💾", name: "floppy disk save" },
      { emoji: "💿", name: "optical disc cd" },
      { emoji: "📀", name: "dvd" },
      { emoji: "📷", name: "camera" },
      { emoji: "📹", name: "video camera record" },
      { emoji: "🎥", name: "movie camera" },
      { emoji: "📞", name: "telephone receiver" },
      { emoji: "☎️", name: "telephone" },
      { emoji: "📺", name: "television" },
      { emoji: "📻", name: "radio broadcast" },
      { emoji: "🎙", name: "studio microphone podcast" },
      { emoji: "🎛", name: "control knobs config dashboard" },
      { emoji: "📡", name: "satellite antenna observability monitor" },
      // Time
      { emoji: "⏰", name: "alarm clock reminder" },
      { emoji: "⏱", name: "stopwatch timer" },
      { emoji: "⌛", name: "hourglass done" },
      { emoji: "⏳", name: "hourglass flowing wait" },
      // Power & utilities
      { emoji: "🔋", name: "battery" },
      { emoji: "🔌", name: "plug power infrastructure setup provisioning" },
      { emoji: "💡", name: "light bulb idea insight" },
      { emoji: "🔦", name: "flashlight torch" },
      { emoji: "🕯", name: "candle" },
      { emoji: "🧯", name: "fire extinguisher mitigation" },
      // Money & commerce
      { emoji: "💸", name: "money flying invoicing payment cash" },
      { emoji: "💰", name: "money bag finance" },
      { emoji: "💳", name: "credit card payment billing" },
      { emoji: "🪙", name: "coin currency" },
      { emoji: "💎", name: "gem diamond premium" },
      { emoji: "⚖️", name: "balance scale legal compliance fairness" },
      // Tools — engineer/devops/qa
      { emoji: "🧰", name: "toolbox" },
      { emoji: "🔧", name: "wrench tool devops fix" },
      { emoji: "🔨", name: "hammer build" },
      { emoji: "🛠", name: "tools build implementation maker" },
      { emoji: "⚙️", name: "gear settings config system slice execution" },
      { emoji: "🧲", name: "magnet attract retain" },
      { emoji: "🪛", name: "screwdriver adjust" },
      { emoji: "🔩", name: "nut and bolt component" },
      // Science & quality gates
      { emoji: "🔬", name: "microscope research lab discovery analysis" },
      { emoji: "🔭", name: "telescope observe long view" },
      { emoji: "⚗️", name: "alembic experiment chemistry" },
      { emoji: "🧪", name: "test tube experiment validation quality gate" },
      { emoji: "🧬", name: "dna genetics core" },
      { emoji: "🦠", name: "microbe germ" },
      { emoji: "💊", name: "pill medicine" },
      { emoji: "💉", name: "syringe shot inject" },
      { emoji: "🌡", name: "thermometer temperature health" },
      // Security & access
      { emoji: "🔑", name: "key access auth" },
      { emoji: "🗝", name: "old key" },
      { emoji: "🔐", name: "locked with key secure governance" },
      { emoji: "🔒", name: "locked secure" },
      { emoji: "🔓", name: "unlocked open public" },
      { emoji: "🛡", name: "shield protect security" },
      // Logistics
      { emoji: "🛒", name: "shopping cart" },
      { emoji: "🛍", name: "shopping bags" },
      { emoji: "🎁", name: "gift wrapped" },
      { emoji: "🎈", name: "balloon" },
      { emoji: "🎉", name: "party popper celebrate ship" },
      { emoji: "🎊", name: "confetti ball celebrate" },
      { emoji: "📦", name: "package box ship deliver release" },
      { emoji: "🏷", name: "label tag category" },
      // Communication & mail
      { emoji: "✉️", name: "envelope mail" },
      { emoji: "📧", name: "email outbound" },
      { emoji: "📨", name: "incoming envelope inbox" },
      { emoji: "📩", name: "envelope with arrow send" },
      { emoji: "📬", name: "open mailbox flag" },
      { emoji: "📤", name: "outbox tray send" },
      { emoji: "📥", name: "inbox tray receive" },
      // Documents — Playbook bread & butter
      { emoji: "📜", name: "scroll document policy" },
      { emoji: "📄", name: "document page playbook procedure guide" },
      { emoji: "📃", name: "page with curl" },
      { emoji: "📑", name: "bookmark tabs sections" },
      { emoji: "🧾", name: "receipt invoice ledger record" },
      { emoji: "📊", name: "bar chart analytics observability metrics" },
      { emoji: "📈", name: "chart up trending growth demand" },
      { emoji: "📉", name: "chart down decline" },
      { emoji: "🗒", name: "spiral notepad notes" },
      { emoji: "🗓️", name: "spiral calendar schedule planning" },
      { emoji: "📅", name: "calendar date" },
      { emoji: "📆", name: "tear off calendar schedule" },
      { emoji: "🗑", name: "wastebasket trash delete" },
      { emoji: "🗃", name: "card file box archive" },
      { emoji: "🗳", name: "ballot box vote decision" },
      { emoji: "🗄", name: "file cabinet archive" },
      { emoji: "📋", name: "clipboard checklist pm tasks" },
      { emoji: "📁", name: "folder closed" },
      { emoji: "📂", name: "folder open" },
      { emoji: "🗂️", name: "card index dividers organize project" },
      { emoji: "🗞", name: "rolled newspaper" },
      { emoji: "📰", name: "newspaper news content" },
      { emoji: "📓", name: "notebook journal postmortem retro" },
      { emoji: "📔", name: "notebook with cover" },
      { emoji: "📒", name: "ledger" },
      { emoji: "📕", name: "closed book red" },
      { emoji: "📗", name: "green book" },
      { emoji: "📘", name: "blue book" },
      { emoji: "📙", name: "orange book" },
      { emoji: "📚", name: "books library knowledge reference" },
      { emoji: "📖", name: "open book read" },
      { emoji: "🔖", name: "bookmark" },
      { emoji: "🔗", name: "link chain url" },
      { emoji: "📎", name: "paperclip attach" },
      { emoji: "📐", name: "triangular ruler spec design" },
      { emoji: "📏", name: "straight ruler spec measure" },
      { emoji: "🧮", name: "abacus calculate" },
      { emoji: "📌", name: "pin important reference anchor" },
      { emoji: "📍", name: "round pin location" },
      { emoji: "✂️", name: "scissors cut" },
      { emoji: "🖊", name: "pen write" },
      { emoji: "🖋", name: "fountain pen sign" },
      { emoji: "✒️", name: "black nib" },
      { emoji: "🖌", name: "paintbrush art" },
      { emoji: "🖍", name: "crayon" },
      { emoji: "📝", name: "memo writing edit notes problem statement" },
      { emoji: "✏️", name: "pencil edit draft" },
      { emoji: "🔍", name: "magnifying glass left search audit review researcher" },
      { emoji: "🔎", name: "magnifying glass right search" },
      { emoji: "🧭", name: "compass navigation direction strategist" },
      { emoji: "🗺", name: "world map plan route" },
      { emoji: "🪧", name: "placard sign announcement" },
      { emoji: "🧱", name: "brick foundation system base" },
    ],
  },
  {
    id: "smileys",
    label: "Smileys & People",
    icon: "😀",
    emojis: [
      { emoji: "😀", name: "grinning face" },
      { emoji: "😃", name: "smiling face open mouth" },
      { emoji: "😄", name: "smiling face open eyes" },
      { emoji: "😁", name: "beaming face" },
      { emoji: "😆", name: "grinning squinting" },
      { emoji: "🤣", name: "rolling on the floor laughing" },
      { emoji: "😂", name: "tears of joy" },
      { emoji: "🙂", name: "slightly smiling" },
      { emoji: "🙃", name: "upside down" },
      { emoji: "😉", name: "winking" },
      { emoji: "😊", name: "smiling blush" },
      { emoji: "😇", name: "halo angel" },
      { emoji: "🥰", name: "smiling hearts love" },
      { emoji: "😍", name: "heart eyes love" },
      { emoji: "🤩", name: "star struck" },
      { emoji: "😋", name: "yum tongue" },
      { emoji: "🤪", name: "zany silly" },
      { emoji: "🤓", name: "nerd glasses smart" },
      { emoji: "🧐", name: "monocle thinking inspect review" },
      { emoji: "🤔", name: "thinking" },
      { emoji: "🤨", name: "raised eyebrow skeptical" },
      { emoji: "😐", name: "neutral" },
      { emoji: "😴", name: "sleeping" },
      { emoji: "🤯", name: "mind blown exploding" },
      { emoji: "😱", name: "scream shock" },
      { emoji: "😢", name: "crying" },
      { emoji: "🥳", name: "partying celebrate" },
      { emoji: "😎", name: "cool sunglasses" },
      { emoji: "🤡", name: "clown" },
      { emoji: "🤠", name: "cowboy" },
      { emoji: "🥸", name: "disguise" },
      { emoji: "💀", name: "skull dead" },
      { emoji: "👻", name: "ghost" },
      { emoji: "👽", name: "alien" },
      { emoji: "🤖", name: "robot agent ai automation" },
      // Hands & gestures
      { emoji: "👋", name: "wave hand hello greeting" },
      { emoji: "🤝", name: "handshake agreement deal sales partner" },
      { emoji: "👌", name: "ok hand approval" },
      { emoji: "✌️", name: "victory peace win" },
      { emoji: "🤞", name: "fingers crossed luck" },
      { emoji: "🤟", name: "love you hand" },
      { emoji: "🤘", name: "rock on horns" },
      { emoji: "👈", name: "point left" },
      { emoji: "👉", name: "point right" },
      { emoji: "👆", name: "point up" },
      { emoji: "👇", name: "point down" },
      { emoji: "👍", name: "thumbs up like approve" },
      { emoji: "👎", name: "thumbs down dislike reject" },
      { emoji: "✊", name: "raised fist" },
      { emoji: "👊", name: "fist bump" },
      { emoji: "🙏", name: "pray thanks please" },
      { emoji: "👏", name: "clapping applause approve" },
      { emoji: "🙌", name: "raising hands celebrate" },
      { emoji: "💪", name: "muscle strong flex power" },
      { emoji: "🧠", name: "brain thinking reasoning strategy" },
      { emoji: "👀", name: "eyes look watching review" },
      { emoji: "👁", name: "eye see observe" },
      { emoji: "🦾", name: "mechanical arm strength" },
      // Roles & professions (heavily weighted — most useful for Skills)
      { emoji: "🧑", name: "person" },
      { emoji: "🧑‍💻", name: "developer technologist coder builder engineer" },
      { emoji: "👨‍💻", name: "man developer engineer" },
      { emoji: "👩‍💻", name: "woman developer engineer" },
      { emoji: "🧑‍💼", name: "office worker manager pm product business" },
      { emoji: "🧑‍🔬", name: "scientist research lab discovery" },
      { emoji: "🧑‍🚀", name: "astronaut explorer launch pioneer" },
      { emoji: "🧑‍🎨", name: "artist designer creative" },
      { emoji: "🧑‍🏫", name: "teacher educator trainer" },
      { emoji: "🧑‍⚖️", name: "judge legal compliance governance review" },
      { emoji: "🧑‍🍳", name: "cook chef recipe" },
      { emoji: "🧑‍🔧", name: "mechanic engineer fix devops infra repair" },
      { emoji: "🧑‍🏭", name: "factory worker operator ops" },
      { emoji: "🧑‍🌾", name: "farmer growth cultivate" },
      { emoji: "🧑‍🚒", name: "firefighter incident emergency oncall" },
      { emoji: "🧑‍✈️", name: "pilot navigator flight" },
      { emoji: "🧑‍⚕️", name: "health worker medical doctor nurse care" },
      { emoji: "🧑‍🎓", name: "graduate learner education" },
      { emoji: "🧑‍🎤", name: "singer performer stage" },
      { emoji: "👮", name: "police officer enforcement" },
      { emoji: "🕵️", name: "detective investigate audit" },
      { emoji: "💂", name: "guard security" },
      { emoji: "👷", name: "construction worker builder" },
      { emoji: "🤴", name: "prince leader" },
      { emoji: "👸", name: "princess leader" },
      { emoji: "🦸", name: "superhero champion" },
      { emoji: "🦹", name: "supervillain antagonist" },
      { emoji: "🥷", name: "ninja stealth" },
      { emoji: "🧙", name: "mage wizard expert" },
    ],
  },
  {
    id: "nature",
    label: "Animals & Nature",
    icon: "🐶",
    emojis: [
      { emoji: "🐶", name: "dog puppy loyal" },
      { emoji: "🐱", name: "cat kitten" },
      { emoji: "🦊", name: "fox clever" },
      { emoji: "🐻", name: "bear" },
      { emoji: "🐼", name: "panda" },
      { emoji: "🐨", name: "koala" },
      { emoji: "🐯", name: "tiger" },
      { emoji: "🦁", name: "lion leader" },
      { emoji: "🐮", name: "cow" },
      { emoji: "🐷", name: "pig" },
      { emoji: "🐸", name: "frog" },
      { emoji: "🐵", name: "monkey" },
      { emoji: "🐔", name: "chicken" },
      { emoji: "🐧", name: "penguin" },
      { emoji: "🦅", name: "eagle vision" },
      { emoji: "🦉", name: "owl wisdom" },
      { emoji: "🦄", name: "unicorn magic rare" },
      { emoji: "🐝", name: "bee busy worker" },
      { emoji: "🦋", name: "butterfly transform" },
      { emoji: "🐢", name: "turtle slow steady" },
      { emoji: "🐙", name: "octopus multitask" },
      { emoji: "🐳", name: "whale big" },
      { emoji: "🦈", name: "shark hunter" },
      { emoji: "🐺", name: "wolf pack" },
      { emoji: "🐎", name: "horse fast" },
      { emoji: "🌵", name: "cactus desert" },
      { emoji: "🌲", name: "evergreen tree" },
      { emoji: "🌳", name: "tree" },
      { emoji: "🌱", name: "seedling growth start grow" },
      { emoji: "🌿", name: "herb leaf branch" },
      { emoji: "🍀", name: "four leaf clover luck" },
      { emoji: "🌷", name: "tulip" },
      { emoji: "🌹", name: "rose" },
      { emoji: "🌻", name: "sunflower" },
      { emoji: "🌸", name: "cherry blossom" },
      { emoji: "🍄", name: "mushroom" },
      { emoji: "🌍", name: "earth globe world" },
      { emoji: "🌐", name: "globe network online web" },
      { emoji: "🌞", name: "sun face bright" },
      { emoji: "☀️", name: "sun bright" },
      { emoji: "⭐", name: "star" },
      { emoji: "🌟", name: "glowing star featured" },
      { emoji: "✨", name: "sparkles polish quality magic" },
      { emoji: "⚡", name: "lightning fast quick instant builder" },
      { emoji: "🔥", name: "fire hot trending incident" },
      { emoji: "💧", name: "water drop" },
      { emoji: "🌊", name: "wave ocean flow" },
      { emoji: "❄️", name: "snowflake cold unique" },
      { emoji: "🌈", name: "rainbow diversity" },
    ],
  },
  {
    id: "food",
    label: "Food & Drink",
    icon: "🍎",
    emojis: [
      { emoji: "🍎", name: "apple red" },
      { emoji: "🍐", name: "pear" },
      { emoji: "🍊", name: "orange" },
      { emoji: "🍋", name: "lemon" },
      { emoji: "🍌", name: "banana" },
      { emoji: "🍉", name: "watermelon" },
      { emoji: "🍇", name: "grapes" },
      { emoji: "🍓", name: "strawberry" },
      { emoji: "🍒", name: "cherries" },
      { emoji: "🍑", name: "peach" },
      { emoji: "🍍", name: "pineapple" },
      { emoji: "🥝", name: "kiwi" },
      { emoji: "🥑", name: "avocado" },
      { emoji: "🥦", name: "broccoli" },
      { emoji: "🌽", name: "corn" },
      { emoji: "🌶", name: "chili pepper hot spicy" },
      { emoji: "🧀", name: "cheese" },
      { emoji: "🥚", name: "egg" },
      { emoji: "🍳", name: "fried egg cooking" },
      { emoji: "🥞", name: "pancakes stack" },
      { emoji: "🍔", name: "burger" },
      { emoji: "🍟", name: "fries" },
      { emoji: "🍕", name: "pizza slice" },
      { emoji: "🌮", name: "taco" },
      { emoji: "🍣", name: "sushi" },
      { emoji: "🍰", name: "cake slice" },
      { emoji: "🎂", name: "birthday cake" },
      { emoji: "🍩", name: "donut" },
      { emoji: "🍪", name: "cookie" },
      { emoji: "🍿", name: "popcorn" },
      { emoji: "☕", name: "coffee hot drink" },
      { emoji: "🍵", name: "tea" },
      { emoji: "🥤", name: "soft drink cup straw" },
      { emoji: "🍺", name: "beer" },
      { emoji: "🍷", name: "wine" },
      { emoji: "🥂", name: "champagne toast cheers" },
      { emoji: "🍾", name: "champagne bottle celebrate launch" },
    ],
  },
  {
    id: "activities",
    label: "Activities",
    icon: "⚽",
    emojis: [
      { emoji: "⚽", name: "soccer ball" },
      { emoji: "🏀", name: "basketball" },
      { emoji: "🏈", name: "football american" },
      { emoji: "⚾", name: "baseball" },
      { emoji: "🎾", name: "tennis" },
      { emoji: "🏐", name: "volleyball" },
      { emoji: "🎱", name: "pool 8 ball" },
      { emoji: "🏓", name: "ping pong" },
      { emoji: "🥊", name: "boxing glove fight" },
      { emoji: "🥋", name: "martial arts discipline" },
      { emoji: "🎯", name: "target dart bullseye goal focus scope icp" },
      { emoji: "🎮", name: "game controller play" },
      { emoji: "🕹", name: "joystick" },
      { emoji: "🎲", name: "die game random" },
      { emoji: "🧩", name: "puzzle piece part" },
      { emoji: "🃏", name: "joker card wild" },
      { emoji: "🎭", name: "performing arts theater" },
      { emoji: "🎨", name: "artist palette art design ux ui" },
      { emoji: "🎬", name: "clapper film movie shoot" },
      { emoji: "🎤", name: "microphone speak announce" },
      { emoji: "🎧", name: "headphones support listen audio" },
      { emoji: "🎼", name: "musical score" },
      { emoji: "🎹", name: "piano keyboard" },
      { emoji: "🥁", name: "drum rhythm" },
      { emoji: "🎸", name: "guitar" },
      { emoji: "🎻", name: "violin" },
      { emoji: "🏆", name: "trophy win victory" },
      { emoji: "🥇", name: "gold medal first" },
      { emoji: "🥈", name: "silver medal second" },
      { emoji: "🥉", name: "bronze medal third" },
      { emoji: "🎖", name: "military medal honor" },
      { emoji: "🎗", name: "reminder ribbon" },
    ],
  },
  {
    id: "travel",
    label: "Travel & Places",
    icon: "🚗",
    emojis: [
      { emoji: "🚗", name: "car automobile" },
      { emoji: "🚕", name: "taxi" },
      { emoji: "🚌", name: "bus" },
      { emoji: "🏎", name: "race car fast" },
      { emoji: "🚓", name: "police car" },
      { emoji: "🚑", name: "ambulance emergency oncall" },
      { emoji: "🚒", name: "fire truck incident" },
      { emoji: "🚚", name: "delivery truck shipping logistics" },
      { emoji: "🚜", name: "tractor farm" },
      { emoji: "🚲", name: "bicycle" },
      { emoji: "🛴", name: "scooter kick" },
      { emoji: "🏍", name: "motorcycle" },
      { emoji: "🚀", name: "rocket launch ship release" },
      { emoji: "🛸", name: "ufo flying saucer experimental" },
      { emoji: "🚁", name: "helicopter" },
      { emoji: "✈️", name: "airplane flight" },
      { emoji: "🛳", name: "passenger ship" },
      { emoji: "⛵", name: "sailboat" },
      { emoji: "🚂", name: "train locomotive pipeline" },
      { emoji: "🏠", name: "house" },
      { emoji: "🏡", name: "house with garden home" },
      { emoji: "🏢", name: "office building enterprise" },
      { emoji: "🏭", name: "factory production" },
      { emoji: "🏥", name: "hospital" },
      { emoji: "🏦", name: "bank finance" },
      { emoji: "🏪", name: "convenience store retail" },
      { emoji: "🏫", name: "school" },
      { emoji: "🏛", name: "classical building institution" },
      { emoji: "🏰", name: "castle" },
      { emoji: "🌃", name: "night with stars" },
      { emoji: "🏙", name: "cityscape" },
      { emoji: "🌅", name: "sunrise start morning" },
      { emoji: "🌉", name: "bridge connect" },
      { emoji: "🌌", name: "milky way galaxy" },
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    icon: "❤️",
    emojis: [
      { emoji: "❤️", name: "red heart love" },
      { emoji: "🧡", name: "orange heart" },
      { emoji: "💛", name: "yellow heart" },
      { emoji: "💚", name: "green heart" },
      { emoji: "💙", name: "blue heart" },
      { emoji: "💜", name: "purple heart" },
      { emoji: "🖤", name: "black heart" },
      { emoji: "🤍", name: "white heart" },
      { emoji: "💔", name: "broken heart" },
      { emoji: "💕", name: "two hearts" },
      { emoji: "💖", name: "sparkling heart favorite" },
      { emoji: "💯", name: "hundred points perfect score" },
      { emoji: "✅", name: "check mark green done approved qa pass" },
      { emoji: "✔️", name: "check mark" },
      { emoji: "☑️", name: "ballot box check" },
      { emoji: "❌", name: "cross mark wrong fail" },
      { emoji: "❎", name: "cross mark button" },
      { emoji: "⭕", name: "hollow red circle" },
      { emoji: "🛑", name: "stop sign halt" },
      { emoji: "⛔", name: "no entry blocked" },
      { emoji: "🚫", name: "prohibited not allowed" },
      { emoji: "🚨", name: "police light alert siren urgent triage incident" },
      { emoji: "📛", name: "name badge" },
      { emoji: "⚠️", name: "warning caution" },
      { emoji: "❗", name: "exclamation alert" },
      { emoji: "❓", name: "question" },
      { emoji: "‼️", name: "double exclamation" },
      { emoji: "⁉️", name: "exclamation question" },
      { emoji: "💢", name: "anger frustration" },
      { emoji: "♻️", name: "recycle reuse loop" },
      { emoji: "💹", name: "chart increasing yen growth" },
      { emoji: "❇️", name: "sparkle new" },
      { emoji: "✳️", name: "eight spoked asterisk" },
      { emoji: "💠", name: "diamond shape" },
      { emoji: "🌀", name: "cyclone spiral loading" },
      { emoji: "💤", name: "zzz sleep idle" },
      { emoji: "ℹ️", name: "information info" },
      { emoji: "🆗", name: "ok button" },
      { emoji: "🆙", name: "up arrow up button upgrade" },
      { emoji: "🆒", name: "cool button" },
      { emoji: "🆕", name: "new button" },
      { emoji: "🆓", name: "free button" },
      { emoji: "▶️", name: "play arrow start" },
      { emoji: "⏸", name: "pause" },
      { emoji: "⏹", name: "stop button" },
      { emoji: "⏺", name: "record button" },
      { emoji: "⏭", name: "next track skip" },
      { emoji: "⏮", name: "previous track" },
      { emoji: "⏩", name: "fast forward" },
      { emoji: "⏪", name: "rewind" },
      { emoji: "🔼", name: "up button" },
      { emoji: "🔽", name: "down button" },
      { emoji: "➡️", name: "right arrow next" },
      { emoji: "⬅️", name: "left arrow back" },
      { emoji: "⬆️", name: "up arrow" },
      { emoji: "⬇️", name: "down arrow" },
      { emoji: "🔀", name: "shuffle randomize" },
      { emoji: "🔁", name: "repeat loop" },
      { emoji: "🔄", name: "counterclockwise arrows refresh sync" },
      { emoji: "🔃", name: "clockwise vertical arrows" },
      { emoji: "➕", name: "plus add new" },
      { emoji: "➖", name: "minus subtract remove" },
      { emoji: "➗", name: "divide" },
      { emoji: "✖️", name: "multiply" },
      { emoji: "💲", name: "dollar" },
      { emoji: "™️", name: "trademark" },
      { emoji: "©️", name: "copyright" },
      { emoji: "®️", name: "registered" },
      { emoji: "🔝", name: "top arrow priority" },
      { emoji: "🔜", name: "soon arrow upcoming" },
      { emoji: "🔴", name: "red circle status critical" },
      { emoji: "🟠", name: "orange circle status warn" },
      { emoji: "🟡", name: "yellow circle status caution" },
      { emoji: "🟢", name: "green circle status ok" },
      { emoji: "🔵", name: "blue circle status info" },
      { emoji: "🟣", name: "purple circle" },
      { emoji: "⚫", name: "black circle" },
      { emoji: "⚪", name: "white circle" },
      { emoji: "🟤", name: "brown circle" },
      { emoji: "🔔", name: "bell notification subscribe" },
      { emoji: "🔕", name: "bell with slash mute silence" },
      { emoji: "📣", name: "megaphone announce" },
      { emoji: "📢", name: "loudspeaker broadcast" },
      { emoji: "💬", name: "speech balloon comment chat" },
      { emoji: "💭", name: "thought balloon idea" },
    ],
  },
  {
    id: "flags",
    label: "Flags",
    icon: "🏁",
    emojis: [
      { emoji: "🏁", name: "checkered flag finish done" },
      { emoji: "🚩", name: "triangular flag milestone" },
      { emoji: "🎌", name: "crossed flags" },
      { emoji: "🏴", name: "black flag" },
      { emoji: "🏳️", name: "white flag" },
      { emoji: "🏳️‍🌈", name: "rainbow flag pride" },
      { emoji: "🏴‍☠️", name: "pirate flag" },
    ],
  },
] as const;

/** Flat list of every emoji in the catalog — convenient for global search. */
export const ALL_EMOJIS: readonly EmojiEntry[] = EMOJI_CATEGORIES.flatMap(
  (cat) => cat.emojis,
);
